version: '3.9'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: my_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "home-library"
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "password"

    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
