version: '3.9'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: my_db
    image: postgres
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      POSTGRES_DB: "go_movies"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"

    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "5432:5432"